// This file was auto-generated by the Witnet compiler, any manual changes will be overwritten except
// each contracts' constructor arguments (you can freely edit those and the compiler will respect them).
const Witnet = artifacts.require('Witnet');
const WitnetRequestsBoardProxy = artifacts.require('WitnetRequestsBoardProxy');
const Season = artifacts.require('Season');
module.exports = function (deployer) {
  deployer.link(Witnet, [Season]);
  deployer.deploy(Season, WitnetRequestsBoardProxy.address, 20, 0, 0);
};
