// This file was auto-generated by the Witnet compiler, any manual changes will be overwritten except
// each contracts' constructor arguments (you can freely edit those and the compiler will respect them).
const Witnet = artifacts.require('Witnet');
const WitnetRequestsBoardProxy = artifacts.require('WitnetRequestsBoardProxy');
const Season = artifacts.require('Season');
module.exports = function (deployer) {
  deployer.link(Witnet, [Season]);
  const wbi = WitnetRequestsBoardProxy.address;
  const noOfTeams = 20;
  const betFee = 1000000000000000; // web3.utils.toWei('0.001', 'ether').toNumber();
  const matchBuildUpDuration = 1 * 60 * 60; // seconds
  deployer.deploy(Season, wbi, noOfTeams, betFee, matchBuildUpDuration);
};
